name: Admin CI
on:
  push:
    paths:
      - "admin/**"
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: "14"
      - name: Install dependencies
        working-directory: ./admin
        run: npm install
      - name: Code linting
        working-directory: ./admin
        run: npm run lint
      - name: Run Tests
        working-directory: ./admin
        run: npm test
#      - name: Run Web Tests
#        working-directory: ./admin
#        run: yarn cypress:runw
#      - name: Deploy
#        working-directory: ./admin
#        run: yarn cypress:runw
