name: API CI
on:
  push:
    paths:
      - "api/**"
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: "14"
      - uses: act10ns/slack@v1.2.2
      - name: Install dependencies
        working-directory: ./api
        run: npm install
      - name: Code linting
        working-directory: ./api
        run: npm run lint
      - name: Run Tests
        working-directory: ./api
        run: npm test
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#      - name: Deploy
#        working-directory: ./map
#        run: yarn cypress:run
