name: Map CI
on:
  push:
    paths:
      - "map/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: "14"
      - name: Install dependencies
        working-directory: ./map
        run: npm install
      - name: Code linting
        working-directory: ./map
        run: npm lint
      - name: Run Tests
        working-directory: ./map
        run: npm test
#      - name: Run Web Tests
#        working-directory: ./map
#        run: yarn cypress:runw
#      - name: Deploy
#        working-directory: ./map
#        run: yarn cypress:runw
