name: Map CI
on:
  push:
    paths:
      - "map/**"
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: "14"
      - uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: teikei-notifications
          status: STARTED
          color: good
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      - name: Install dependencies
        working-directory: ./map
        run: npm install
      - name: Code linting
        working-directory: ./map
        run: npm run lint
      - name: Run Tests
        working-directory: ./map
        run: npm test
      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: teikei-notifications
          status: SUCCESS
          color: good
      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: teikei-notifications
          status: FAILED
          color: danger
#      - name: Run Web Tests
#        working-directory: ./map
#        run: yarn cypress:runw
#      - name: Deploy
#        working-directory: ./map
#        run: yarn cypress:runw
